### ISSUE TITLE
How to login to Azure AD ?

### ISSUE THREAD

**Issue by wittawatu** [btargac/excel-parser-processor#230]
How to login to the web if it is requires Azure AD with Multi factor authen?

**Comment by btargac** [comment]
you mean while fetching some assets from a URL that requires authentication ?

**Comment by wittawatu** [comment]
Yes,Thank you,Wittawat UtsadeeOn 13 Oct 2022, at 20:50, Burak Targaç ***@***.***> wrote:﻿
you mean while fetching some assets from a URL that requires authentication ?

**Comment by btargac** [comment]
This is not something I acknowledged before, if this app makes a request to the server to fetch an image or a file with a known extension and instead gets something different for example it can be html response asking to login in your case then it saves the response as an HTML files I guess, is it the case ?

**Comment by btargac** [comment]
I guess there will be multiple platforms as a service (Azure, Amazon, Google Drive etc.) and they can require different authorization methods or captchas since this electron based browser won't be recognized for the first time by those providers, so showing a modal on the very first 40x status code won't solve the problem. In my opinion for now all the assets should be public and not require any authentication. If there are no objections from your side @wittawatu I'll close the issue.
